puppetmaster:
  build: build/puppetmaster
  hostname: puppetmaster
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker

#centos5:
#  build: build/centos5
#  links:
#    - puppetmaster

centos6:
  build: build/centos6
  links:
    - puppetmaster

centos7:
  build: build/centos7
  links:
    - puppetmaster
